firewall:
  # metrics
  - port: '44321/tcp'
    state: enabled
  # logging
  - port: '514/tcp'
    state: enabled
  - port: '20514/tcp'
    state: enabled
  # nfs
  - service: nfs
    state: enabled
  # ipsec/vpn
  - service: ipsec
    state: enabled
