logging_inputs:
  - name: system_input
    type: basics
logging_outputs:
  - name: relp_client
    type: relp
    target: "{{ logging_server }}"
    tls: true
    ca_cert: /etc/pki/ca-trust/source/anchors/demo-ca.crt
    cert: /etc/pki/tls/certs/{{ inventory_hostname }}.crt
    private_key: /etc/pki/tls/private/{{ inventory_hostname }}.key
    permitted_servers:
      - "*.{{ logging_domain }}"
logging_flows:
  - name: flow
    inputs: [system_input]
    outputs: [relp_client]
