sshd_gssapi_authentication: 'yes'
sshd_gssapi_cleanup_credentials: 'no'
sshd_kerberos_authentication: 'no'
sshd_password_authentication: 'no'
sshd_pubkey_authentication: 'yes'
sshd_syslog_facility: AUTHPRIV
sshd_use_dns: 'no'
sshd_use_pam: 'yes'
sshd_x11_forwarding: 'no'
sshd_rekey_limit: '512M 1h'
sshd_max_sessions: 10
sshd_max_startups: 10:30:100
sshd_max_auth_tries: 6
sshd_client_alive_interval: 600
sshd_client_alive_count_max: 3
